apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
#    url: timescaledb:5432
    url: http://localhost:5433
    database: mydb
    user: myuser
    secureJsonData:
      password: mypassword
    jsonData:
      sslmode: "disable"
      postgresVersion: 1400
      timescaledb: true
