version: '3.8'

services:

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: timescaledb
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "8083:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
    command: [ "postgres", "-c", "listen_addresses=*" ]


  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "8082:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./docker/config/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - timescaledb
    environment:
      - GF_SERVER_HTTP_ADDR=0.0.0.0

volumes:
  timescale_data:
  grafana_data:
